**Importing needed libraries**

In [395]:
import numpy as np
import pandas as pd

In [396]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, StandardScaler, Normalizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import Normalizer
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.layers import BatchNormalization
from keras.utils import np_utils
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.optimizers import RMSprop
from keras.regularizers import l2
from sklearn.model_selection import cross_val_score
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV

In [298]:
#pip install scikeras

In [397]:
df = pd.read_csv("/content/drive/MyDrive/Assignment 4/roo_data.csv")

In [398]:
df.head()

Acedamic percentage in Operating Systems  ...              Suggested Job Role
0                                        69  ...              Database Developer
1                                        78  ...            Portal Administrator
2                                        71  ...            Portal Administrator
3                                        76  ...  Systems Security Administrator
4                                        92  ...        Business Systems Analyst

[5 rows x 39 columns]

**Data Describe**

In [399]:
print(df.columns)

Index(['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Rea

In [403]:
print("Number of rows ::", len(df))
print("Number of columns ::", len(df.columns))
print("Number of rows and columns ::", len(df.shape))
print("Number of elements ::", df.size)

Number of rows :: 20000
Number of columns :: 39
Number of rows and columns :: 2
Number of elements :: 780000


In [404]:
df.isnull().sum()

Acedamic percentage in Operating Systems    0
percentage in Algorithms                    0
Percentage in Programming Concepts          0
Percentage in Software Engineering          0
Percentage in Computer Networks             0
Percentage in Electronics Subjects          0
Percentage in Computer Architecture         0
Percentage in Mathematics                   0
Percentage in Communication skills          0
Hours working per day                       0
Logical quotient rating                     0
hackathons                                  0
coding skills rating                        0
public speaking points                      0
can work long time before system?           0
self-learning capability?                   0
Extra-courses did                           0
certifications                              0
workshops                                   0
talenttests taken?                          0
olympiads                                   0
reading and writing skills        

**Replacing values of the columns**

In [405]:
rep_cert_val = {'shell programming' : 'distro making', 
                'distro making' : 'distro making',
               'machine learning' : 'machine learning' ,
                'python': 'machine learning' ,
                'r programming' : 'machine learning',
               }

In [406]:
df = df.replace({'certifications' : rep_cert_val})

In [407]:
rep_sub_val = {'data engineering' : 'engineering',
              'Software Engineering' : 'engineering'}

In [408]:
df = df.replace({'Interested subjects' : rep_sub_val})

In [409]:
rep_book_val = {'Prayer books' : 'non fiction books', 
                'Religion-Spirituality' : 'non fiction books', 
                'Guide' : 'non fiction books', 
                'Self help' : 'non fiction books',
                'Math' : 'refrence books for studies', 
                'Science' : 'refrence books for studies', 
                'History' : 'refrence books for studies',
                'Art' : 'non fiction books',
                'Childrens' : 'fiction books',
                'Travel' : 'fiction books', 
                'Comics' : 'fiction books',
               'Romance' : 'fiction books', 
                'Drama' : 'fiction books',
                'Fantasy' : 'fiction books',
                'Satire' : 'fiction books',
                'Science fiction' : 'fiction books',
               'Action and Adventure' : 'fiction books',
                'Mystery' : 'fiction books',
                'Horror' : 'fiction books',
               'Cookbooks' : 'non fiction books',
                'Health' : 'non fiction books',
               'Anthology' : 'literature book',
                'Poetry' : 'literature book',
                'Diaries' : 'literature book',
                'Journals' : 'literature book',
               'Autobiographies' : 'literature books',
                'Biographies' : 'literature books',
               'Encyclopedias' : 'tertiary source',
                'Dictionaries' : 'tertiary source',
               'Series' : 'fiction books',
                'Trilogy' : 'fiction books'}

In [410]:
df = df.replace({'Interested Type of Books' : rep_book_val})

In [411]:
replace_values = {'Database Developer' : 'Developer',
                  'Web Developer' : 'Developer',
                  'CRM Technical Developer' : 'Developer',
                  'Mobile Applications Developer' : 'Developer',
                  'Software Developer' : 'Developer',
                  'Applications Developer' : 'Developer', 
                  'Portal Administrator' : 'Administrator',
                  'Systems Security Administrator' : 'Administrator',
                  'Network Security Administrator' : 'Administrator',
                  'Database Administrator' : 'Administrator',
                  'Business Systems Analyst' : 'Analyst',
                    'Business Intelligence Analyst' : 'Analyst',
                    'Information Security Analyst' :'Analyst',
                    'CRM Business Analyst' : 'Analyst',
                    'Systems Analyst' : 'Analyst',
                    'Programmer Analyst' : 'Analyst',
                    'E-Commerce Analyst' : 'Analyst',
                  'Software Systems Engineer' : 'Engineer',
                    'Network Engineer' :'Engineer',
                    'Software Engineer' : 'Engineer',
                    'Technical Engineer' : 'Engineer',
                    'Network Security Engineer' : 'Engineer',
                  'UX Designer' : 'Design',
                    'Design & UX' :'Design',
                  'Quality Assurance Associate' : 'Testing',
                    'Software Quality Assurance (QA) / Testing' : 'Testing',
                    'Information Technology Auditor' :'Technical Support',
                  'Technical Support' :'Technical Support',
                    'Technical Services/Help Desk/Tech Support' :'Technical Support',
                  'Project Manager' : 'Administrator',
                    'Information Technology Manager' : 'Administrator',
                    'Database Manager' :'Administrator',
                  'Solutions Architect' :'Design',
                    'Data Architect' :'Design'}

In [412]:
df = df.replace({'Suggested Job Role' : replace_values})

In [413]:
df.tail(2)

Acedamic percentage in Operating Systems  ...  Suggested Job Role
19998                                        68  ...             Testing
19999                                        73  ...           Developer

[2 rows x 39 columns]

**Divide the dataset into features and target**

In [414]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

**Ordinal encoding for converting categorical values of features**

In [415]:
ordinal = OrdinalEncoder()

In [416]:
X_ord = ordinal.fit_transform(X)

**normalizinf features with Normalizer**

In [417]:
X_norm = Normalizer().fit_transform(X_ord)

In [418]:
feature = pd.DataFrame(X_norm, columns=['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert'])

In [419]:
feature.tail()

Acedamic percentage in Operating Systems  ...  Introvert
19995                                  0.422392  ...   0.000000
19996                                  0.334170  ...   0.016708
19997                                  0.340638  ...   0.014810
19998                                  0.132544  ...   0.000000
19999                                  0.217728  ...   0.000000

[5 rows x 38 columns]

**label encoding for converting categorical values of target**

In [420]:
label = LabelEncoder()

In [421]:
y = label.fit_transform(y)

In [422]:
label = pd.DataFrame(y, columns=['Suggested Job Role'])

In [423]:
label = np.ravel(label)
label.shape

(20000,)

## **Keras Model**

In [424]:
trainX, testX, trainy, testy = train_test_split(feature,
                                label,
                                test_size=0.1,
                                random_state=42)

**converted to numpy array with total number of classes are 7**

In [425]:
trainy_cat = np_utils.to_categorical(trainy, num_classes=7)
testy_cat = np_utils.to_categorical(testy, num_classes=7)

In [426]:
print('y_train shape::', trainy_cat.shape)
print('y_test shape::', testy_cat.shape)

y_train shape:: (18000, 7)
y_test shape:: (2000, 7)


**sequential model with 2 hidden layers, batch normalization and dropout(for regularization)**

In [427]:
# define the model
model = Sequential()

model.add(Dense(100, input_dim=trainX.shape[1], activation='relu', kernel_initializer='uniform'))

model.add(Dense(60, activation = 'relu', kernel_initializer='uniform'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(40, activation = 'relu', kernel_initializer='uniform'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(7, activation='softmax', kernel_initializer='uniform'))



In [428]:
# compile the keras model
#decay_rate = 0.1 / 100
#sgd = SGD(learning_rate=0.1, momentum=0.8, decay=decay_rate, nesterov=False)
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])


In [429]:
# fit the keras model on the dataset
model.fit(trainX, trainy_cat, epochs=60, batch_size=250, verbose=2)

Epoch 1/60
72/72 - 1s - loss: 1.9394 - accuracy: 0.1779 - 918ms/epoch - 13ms/step
Epoch 2/60
72/72 - 0s - loss: 1.9243 - accuracy: 0.2204 - 206ms/epoch - 3ms/step
Epoch 3/60
72/72 - 0s - loss: 1.9127 - accuracy: 0.2280 - 220ms/epoch - 3ms/step
Epoch 4/60
72/72 - 0s - loss: 1.9033 - accuracy: 0.2310 - 242ms/epoch - 3ms/step
Epoch 5/60
72/72 - 0s - loss: 1.8957 - accuracy: 0.2309 - 221ms/epoch - 3ms/step
Epoch 6/60
72/72 - 0s - loss: 1.8895 - accuracy: 0.2312 - 217ms/epoch - 3ms/step
Epoch 7/60
72/72 - 0s - loss: 1.8841 - accuracy: 0.2320 - 219ms/epoch - 3ms/step
Epoch 8/60
72/72 - 0s - loss: 1.8802 - accuracy: 0.2302 - 197ms/epoch - 3ms/step
Epoch 9/60
72/72 - 0s - loss: 1.8768 - accuracy: 0.2311 - 232ms/epoch - 3ms/step
Epoch 10/60
72/72 - 0s - loss: 1.8742 - accuracy: 0.2314 - 214ms/epoch - 3ms/step
Epoch 11/60
72/72 - 0s - loss: 1.8718 - accuracy: 0.2308 - 192ms/epoch - 3ms/step
Epoch 12/60
72/72 - 0s - loss: 1.8698 - accuracy: 0.2318 - 187ms/epoch - 3ms/step
Epoch 13/60
72/72 - 0s -

In [430]:
predy = model.predict(testX)
#length = len(predy)
testy_label = np.argmax(testy_cat , axis=1)
predy_label = np.argmax(predy , axis=1)

acc_model = np.sum(testy_label==predy_label)/length * 100
print("Accuracy of the dataset",acc_model )

Accuracy of the dataset 23.799999999999997


In [434]:
model_cm = confusion_matrix(testy_label, predy_label)

In [435]:
print(model_cm)

[[435  32   0   0   0   0   0]
 [341  41   0   0   0   0   0]
 [199  30   0   0   0   0   0]
 [299  46   0   0   0   0   0]
 [254  16   0   0   0   0   0]
 [161  19   0   0   0   0   0]
 [121   6   0   0   0   0   0]]


In [439]:
target_names = ['Class 0', 'Class 1', 'CLass 2', 'Class 3', 'Class 4', 'Class 5', 'Class 6']
model_cr = classification_report(testy_label, predy_label, target_names = target_names)
print(model_cr)

              precision    recall  f1-score   support

     Class 0       0.24      0.93      0.38       467
     Class 1       0.22      0.11      0.14       382
     CLass 2       0.00      0.00      0.00       229
     Class 3       0.00      0.00      0.00       345
     Class 4       0.00      0.00      0.00       270
     Class 5       0.00      0.00      0.00       180
     Class 6       0.00      0.00      0.00       127

    accuracy                           0.24      2000
   macro avg       0.07      0.15      0.08      2000
weighted avg       0.10      0.24      0.12      2000



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## **MLP Classifier**

In [440]:
trainX, testX, trainy, testy = train_test_split(feature,
                                label,
                                test_size=0.1,
                                random_state = 42)

In [441]:
from sklearn.neural_network import MLPClassifier
from sklearn.exceptions import ConvergenceWarning

In [442]:
clf = MLPClassifier(random_state=1, max_iter=300, alpha=1)
clf.fit(trainX, trainy)


MLPClassifier(alpha=1, max_iter=300, random_state=1)

In [443]:
mlp_acc = clf.score(trainX, trainy)
print("MLP Train Accuracy :: ", mlp_acc)

MLP Train Accuracy ::  0.2308888888888889


In [444]:
predy = clf.predict(testX)
mlp_acc = accuracy_score(testy, predy)
print("MLP Test Accuracy :: ", mlp_acc)

MLP Test Accuracy ::  0.2335


In [445]:
model_cm = confusion_matrix(testy, predy)

In [446]:
print("Confusion Matrix for MLP Classifier :: \n", model_cm)

Confusion Matrix for MLP Classifier :: 
 [[467   0   0   0   0   0   0]
 [382   0   0   0   0   0   0]
 [229   0   0   0   0   0   0]
 [345   0   0   0   0   0   0]
 [270   0   0   0   0   0   0]
 [180   0   0   0   0   0   0]
 [127   0   0   0   0   0   0]]


In [447]:
target_names = ['Class 0', 'Class 1', 'CLass 2', 'Class 3', 'Class 4', 'Class 5', 'Class 6']
model_cr = classification_report(testy, predy, target_names = target_names)
print(model_cr)

              precision    recall  f1-score   support

     Class 0       0.23      1.00      0.38       467
     Class 1       0.00      0.00      0.00       382
     CLass 2       0.00      0.00      0.00       229
     Class 3       0.00      0.00      0.00       345
     Class 4       0.00      0.00      0.00       270
     Class 5       0.00      0.00      0.00       180
     Class 6       0.00      0.00      0.00       127

    accuracy                           0.23      2000
   macro avg       0.03      0.14      0.05      2000
weighted avg       0.05      0.23      0.09      2000



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### **KerasClassifier**

In [448]:
trainX, testX, trainy, testy = train_test_split(feature,
                                label,
                                test_size=0.1,
                                random_state = 42)

In [449]:
trainy_cat = np_utils.to_categorical(trainy, num_classes=7)
testy_cat = np_utils.to_categorical(testy, num_classes=7)

In [450]:
print('y_train shape::', trainy_cat.shape)
print('y_test shape::', testy_cat.shape)

y_train shape:: (18000, 7)
y_test shape:: (2000, 7)


In [451]:
# define the model
def create_classifier():
    model = Sequential()

    model.add(Dense(64, input_dim=trainX.shape[1], activation='relu', kernel_initializer='uniform'))

    model.add(Dense(64, activation = 'relu', kernel_initializer='uniform'))
    model.add(BatchNormalization())
    model.add(Dropout(0.2))

    model.add(Dense(64, activation = 'relu', kernel_initializer='uniform'))
    model.add(BatchNormalization())
    model.add(Dropout(0.2))

    model.add(Dense(7, activation='softmax', kernel_initializer='uniform'))

    model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

    return model


In [452]:
keras_classifier = KerasClassifier(build_fn = create_classifier, batch_size = 250, epochs = 100)

In [453]:
accuracy = cross_val_score(estimator = keras_classifier, X = trainX, y = trainy_cat, cv = 5, n_jobs = -1)

In [454]:
acc_mean = accuracy.mean()
print("Mean of Accuracy :: ", acc_mean)

Mean of Accuracy ::  0.2232222222222222


# **GridSearchCV**

In [455]:
parameters = {'batch_size' : [350, 650, 750],
              'epochs' : [60, 150, 350],
              }

grid = GridSearchCV(estimator = keras_classifier, 
                    param_grid = parameters,
                    n_jobs = -1,
                    scoring = "accuracy",
                    cv = 5)

In [456]:
grid = grid.fit(trainX, trainy_cat)

/usr/local/lib/python3.7/dist-packages/scikeras/wrappers.py:290: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  "``build_fn`` will be renamed to ``model`` in a future release,"


Epoch 1/60
28/28 [==============================] - 1s 7ms/step - loss: 1.9439 - accuracy: 0.1556
Epoch 2/60
28/28 [==============================] - 0s 7ms/step - loss: 1.9361 - accuracy: 0.1934
Epoch 3/60
28/28 [==============================] - 0s 8ms/step - loss: 1.9309 - accuracy: 0.2071
Epoch 4/60
28/28 [==============================] - 0s 7ms/step - loss: 1.9253 - accuracy: 0.2179
Epoch 5/60
28/28 [==============================] - 0s 7ms/step - loss: 1.9199 - accuracy: 0.2221
Epoch 6/60
28/28 [==============================] - 0s 7ms/step - loss: 1.9156 - accuracy: 0.2244
Epoch 7/60
28/28 [==============================] - 0s 7ms/step - loss: 1.9109 - accuracy: 0.2246
Epoch 8/60
28/28 [==============================] - 0s 7ms/step - loss: 1.9073 - accuracy: 0.2274
Epoch 9/60
28/28 [==============================] - 0s 7ms/step - loss: 1.9038 - accuracy: 0.2296
Epoch 10/60
28/28 [==============================] - 0s 7ms/step - loss: 1.9005 - accuracy: 0.2292
Epoch 11/60
28/28 [

In [457]:
best_para = grid.best_params_


In [458]:
best_acc = grid.best_score_

In [459]:
print("Best Parameteers ::", best_para)
print("Best Accuracy ::", best_acc)

Best Parameteers :: {'batch_size': 650, 'epochs': 60}
Best Accuracy :: 0.22933333333333333
